// <auto-generated />
using System;
using MeetingManagement.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260215092754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetingManagement.Models.AccountModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreateAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR(150)")
                        .HasColumnName("Password");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("UpdateBy");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("UserId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("MeetingManagement.Models.CompanyModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("Address");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreateAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("Name");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("UpdateBy");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("MeetingManagement.Models.DepartmentModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreateAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("Name");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("UpdateBy");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("MeetingManagement.Models.MeetingModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreateAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("EndAt");

                    b.Property<int>("MeetingStatus")
                        .HasColumnType("int");

                    b.Property<string>("Organization")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("Organization");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("RoomId");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("StartAt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("Title");

                    b.Property<byte>("Type")
                        .HasColumnType("TINYINT")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("UpdateBy");

                    b.Property<string>("Url")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoomId");

                    b.ToTable("Meetings", (string)null);
                });

            modelBuilder.Entity("MeetingManagement.Models.MeetingRoomModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreateAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("Name");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("UpdateBy");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("MeetingRooms", (string)null);
                });

            modelBuilder.Entity("MeetingManagement.Models.PermissionModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<string>("Action")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Action");

                    b.Property<string>("Controller")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Controller");

                    b.Property<bool>("Delete")
                        .HasColumnType("BIT")
                        .HasColumnName("Delete");

                    b.Property<bool>("DeleteAll")
                        .HasColumnType("BIT")
                        .HasColumnName("DeleteAll");

                    b.Property<bool>("Edit")
                        .HasColumnType("BIT")
                        .HasColumnName("Edit");

                    b.Property<bool>("EditAll")
                        .HasColumnType("BIT")
                        .HasColumnName("EditAll");

                    b.Property<bool>("FullPermission")
                        .HasColumnType("BIT")
                        .HasColumnName("FullPermission");

                    b.Property<bool>("Insert")
                        .HasColumnType("BIT")
                        .HasColumnName("Insert");

                    b.Property<bool>("InsertAll")
                        .HasColumnType("BIT")
                        .HasColumnName("InsertAll");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("UserId");

                    b.Property<bool>("View")
                        .HasColumnType("BIT")
                        .HasColumnName("View");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("MeetingManagement.Models.RefreshTokenModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("AccountId");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreateAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("ExpiresAt");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("LoginAt");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("NVARCHAR(1000)")
                        .HasColumnName("ReplacedByToken");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("RevokedAt");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(1000)")
                        .HasColumnName("TokenHash");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("UpdateBy");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("MeetingManagement.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("Address");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("DATE")
                        .HasColumnName("Birthday");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreateAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("FullName");

                    b.Property<byte>("Gender")
                        .HasColumnType("TINYINT")
                        .HasColumnName("Gender");

                    b.Property<string>("Phone")
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Phone");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("UpdateBy");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MeetingUserModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("UserId");

                    b.Property<string>("MeetingId")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("MeetingId");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true)
                        .HasColumnName("IsConfirmed");

                    b.Property<byte>("Role")
                        .HasColumnType("TINYINT")
                        .HasColumnName("Role");

                    b.HasKey("UserId", "MeetingId");

                    b.HasIndex("MeetingId");

                    b.ToTable("MeetingUsers", (string)null);
                });

            modelBuilder.Entity("MeetingManagement.Models.AccountModel", b =>
                {
                    b.HasOne("MeetingManagement.Models.UserModel", "User")
                        .WithOne("Account")
                        .HasForeignKey("MeetingManagement.Models.AccountModel", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeetingManagement.Models.DepartmentModel", b =>
                {
                    b.HasOne("MeetingManagement.Models.CompanyModel", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MeetingManagement.Models.MeetingModel", b =>
                {
                    b.HasOne("MeetingManagement.Models.CompanyModel", "Company")
                        .WithMany("Meetings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MeetingManagement.Models.DepartmentModel", "Department")
                        .WithMany("Meetings")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MeetingManagement.Models.MeetingRoomModel", "MeetingRoom")
                        .WithMany("Meetings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("MeetingRoom");
                });

            modelBuilder.Entity("MeetingManagement.Models.MeetingRoomModel", b =>
                {
                    b.HasOne("MeetingManagement.Models.CompanyModel", "Company")
                        .WithMany("Rooms")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MeetingManagement.Models.PermissionModel", b =>
                {
                    b.HasOne("MeetingManagement.Models.UserModel", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeetingManagement.Models.RefreshTokenModel", b =>
                {
                    b.HasOne("MeetingManagement.Models.AccountModel", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MeetingManagement.Models.UserModel", b =>
                {
                    b.HasOne("MeetingManagement.Models.CompanyModel", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MeetingManagement.Models.DepartmentModel", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MeetingUserModel", b =>
                {
                    b.HasOne("MeetingManagement.Models.MeetingModel", "Meeting")
                        .WithMany("MeetingUser")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MeetingManagement.Models.UserModel", "User")
                        .WithMany("MeetingUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeetingManagement.Models.AccountModel", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("MeetingManagement.Models.CompanyModel", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Meetings");

                    b.Navigation("Rooms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MeetingManagement.Models.DepartmentModel", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MeetingManagement.Models.MeetingModel", b =>
                {
                    b.Navigation("MeetingUser");
                });

            modelBuilder.Entity("MeetingManagement.Models.MeetingRoomModel", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("MeetingManagement.Models.UserModel", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("MeetingUser");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
